### ISSUE TITLE
2. Amit Patel/Git & Github Workflow

### ISSUE THREAD

**Issue by Amitpatel7090** [Amitpatel7090/music-app#1]
### Implement
- [x] #2
- [x] [Git Tutorial for Beginners: Learn Git in 1 Hour](https://www.youtube.com/watch?v=8JJ101D3knE)
- [x] [Github Branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches)
- [x] [Github Pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
- [x] Create Pull request by adding "/start-coding" comment in your issue. This will create branch and PR associated to your issue in Training repo.
- [x] [Pull request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews)
- [x] [Merge pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request)
- [x] [Normal Merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-your-commits)
- [x] [Squash and Merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
- [x] [Rebase and Merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits)
- [x] [Resolve merge conflicts](https://github.com/skills/resolve-merge-conflicts)
- [x] [The EXTREMELY helpful guide to merge conflicts](https://www.youtube.com/watch?v=HosPml1qkrg)
- [x] [Pull request in VSCode](https://www.youtube.com/watch?v=LdSwWxVzUpo)
### Measure
- [x] Basic knowledge of PR
- [x] Review PR
- [x] Merge PR
Replies:

**Comment by Amitpatel7090** [comment]
@beingminimal completed all task and also practiced in
-  [ ] https://github.com/Amitpatel7090/skills-resolve-merge-conflicts

**Comment by beingminimal** [comment]
ok that's good...

Now you can start Rust learning path https://github.com/StaytunedLLP/learning-paths/discussions/categories/rust
